spring.application.name=mcp-playground-client
server.port=8080

spring.ai.mcp.client.streamable-http.connections.local-mcp-playground-server.url=http://localhost:7070
spring.config.import=optional:file:secrets.env[.properties]
spring.web.resources.static-locations=classpath:${section}/static