server.port=8083
candidate-service.url=http://localhost:8081
job-service.url=http://localhost:8082

spring.ai.model.chat=openai
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.config.import=optional:file:secrets.env[.properties]
