spring.application.name=springai-playground

spring.ai.model.chat=openai
spring.ai.openai.chat.options.model=gpt-40-mini
spring.ai.openai.api-key=${OPENAI_API_KEY}

#Load actual keys from this file(if present)
spring.config.import=optional:file:secrets.env