spring.application.name=mcp-playground-client
server.port=8080

spring.ai.mcp.client.streamable-http.connections.city-service.url=http://localhost:7070
spring.ai.mcp.client.streamable-http.connections.flight-service.url=http://localhost:7071
spring.ai.mcp.client.streamable-http.connections.user-service.url=http://localhost:7072
spring.ai.mcp.client.streamable-http.connections.weather-service.url=http://localhost:7073

spring.config.import=optional:file:secrets.env[.properties]
spring.web.resources.static-locations=classpath:${section}/static