server.port=8084
job-service.url=http://localhost:8082

spring.jpa.defer-datasource-initialization=true

spring.ai.model.chat=openai
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.config.import=optional:file:secrets.env[.properties]